version: '2'
services:
  redpanda:
    command:
    - redpanda
    - start
    - --smp
    - '1'
    - --reserve-memory
    - 0M
    - --overprovisioned
    - --node-id
    - '0'
    - --kafka-addr
    - PLAINTEXT://0.0.0.0:29092,OUTSIDE://0.0.0.0:9092
    - --advertise-kafka-addr
    - PLAINTEXT://redpanda:29092,OUTSIDE://localhost:9092
    - --set redpanda.enable_idempotence=true
    - --set redpanda.enable_transactions=true
    # NOTE: Please use the latest version here!
    image: docker.vectorized.io/vectorized/redpanda:v22.1.3
    container_name: redpanda-1
    ports:
    - 8080:8081
    - 9092:9092
    - 29092:29092
  fhir:
    image: docker.io/floodplain/hapi-fhir-jpaserver-starter:latest
    depends_on:
      - redpanda
    ports:
      - 8084:8080
    environment:
      - KAFKA_BOOTSTRAP=redpanda:29092
  kafkaui:
    image: provectuslabs/kafka-ui:latest
    depends_on:
      - redpanda
    ports:
      - 8082:8080
    environment:
      - KAFKA_CLUSTERS_0_NAME=mycluster
      - KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS=redpanda:29092
      - BOOTSTRAP_SERVERS=redpanda:29092
  jobmanager:
    build: flink
    ports:
      - "8081:8081"
    command: jobmanager
    environment:
      - |
        FLINK_PROPERTIES=
        jobmanager.rpc.address: jobmanager
  taskmanager:
    build: flink
    depends_on:
      - jobmanager
    command: taskmanager
    scale: 1
    environment:
      - |
        FLINK_PROPERTIES=
        jobmanager.rpc.address: jobmanager
        taskmanager.numberOfTaskSlots: 4
  sql-client: 
    build: sql-client
    command: bin/sql-client.sh 
    depends_on: 
      - jobmanager
      - taskmanager
    environment:
      - |
        FLINK_PROPERTIES=
        jobmanager.rpc.address: jobmanager
  analytics-postgres:
    build: analytics
    restart: always
    ports:
      - "5435:5432"
    environment:
      POSTGRES_PASSWORD: mysecretpassword
      POSTGRES_DB: analytics
